In [15]:
# Aides utilisées : exemples de Jupyter Notebook + Mistral
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view
from IPython.display import display

mp_key = "kHK7l7itQo2c5bLbQQIsHOTh5cQ7HUnw"
mp_id = "mp-20289"  # NaInS2

# On récupère la structure cristalline à partir de Materials Project
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)  # Structure cristalline primitive(donc la maille primitive)
    conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()  # Structure cristalline conventionnelle (plus grande que la maille primitive)
    symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()  # On obtient les opérations de symétries

# On affiche la structure initiale
print(f"\nImage de la structure cristalline initial\n")
view = quick_view(conv_struc, "packed", conventional=True)
display(view)
view.script('rotate on')

# Fonction pour afficher les coordonnées et la réprésentation avec JSmol
def display_symmetry_operation(i_atom, i_symmop, atom_name, operation_type):
    symmop = symmops[i_symmop]
    matrix = symmop.rotation_matrix

    # On affiche le type d'opération et la matrice de transformation
    print(f"\n{operation_type}\n")
    print(f"Matrice de transformation :\n{matrix}\n")
    print(f"Opération de symétrie pour l'atome {atom_name} (indice {i_atom}) :\n")

    # On calcule les positions initiales et finales de l'atome
    pos_init = conv_struc.sites[i_atom - 1].frac_coords  ##On utilise les indices des positions des atomes
    pos_final = symmop.operate(pos_init)
    print(f"Position initiale de l'atome {atom_name} : {pos_init}")
    print(f"Position finale de l'atome {atom_name} : {pos_final}\n")

    # On affiche la structure après l'opération de symétrie
    view = quick_view(conv_struc, "packed", conventional=True)
    display(view)
    view.script(f'draw SYMOP {i_symmop + 1} {{atomno = {i_atom}}}')

# Réflexion sur l'atome Na
display_symmetry_operation(1, 1, "Na", "Réflexion")

# Rotation sur l'atome In
display_symmetry_operation(5, 2, "In", "Rotation")

# Roto-inversion sur l'atome S
display_symmetry_operation(8, 7, "S", "Roto-inversion")

#pour trouver une matrice de transformation qui correspond à une roto-inversion,j'ai utilisé le fait que Une roto-inversion a une matrice de rotation avec un déterminant de −1 et n'est pas la matrice identité négative
#pour trouver une matrice de transformation qui correspondent à une rotation, j'ai utilisé le fait que Une rotation a une matrice de rotation avec un déterminant de 1 et n'est pas la matrice identité.
#pour trouver une matrice de transformation qui correspondent à une réflexion j'ai utilisé le fait qu'une réflexion a une matrice de rotation avec un déterminant de −1 et au moins un −1 sur la diagonale.

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]


Image de la structure cristalline initial



JsmolView(layout=Layout(align_self='stretch', height='400px'))


Réflexion

Matrice de transformation :
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]

Opération de symétrie pour l'atome Na (indice 1) :

Position initiale de l'atome Na : [0.66666667 0.33333333 0.83333333]
Position finale de l'atome Na : [-0.66666667 -0.33333333 -0.83333333]



JsmolView(layout=Layout(align_self='stretch', height='400px'))


Rotation

Matrice de transformation :
[[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]

Opération de symétrie pour l'atome In (indice 5) :

Position initiale de l'atome In : [0.66666667 0.33333333 0.33333333]
Position finale de l'atome In : [-0.33333333  0.33333333  0.33333333]



JsmolView(layout=Layout(align_self='stretch', height='400px'))


Roto-inversion

Matrice de transformation :
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]

Opération de symétrie pour l'atome S (indice 8) :

Position initiale de l'atome S : [0.33333333 0.66666667 0.92628399]
Position finale de l'atome S : [-0.66666667 -0.33333333  0.92628399]



JsmolView(layout=Layout(align_self='stretch', height='400px'))